### ISSUE TITLE
A puzzle about mojofm implementation of maxDistanceTo

### ISSUE THREAD

**Issue by hh23485** [HUSACCT/HUSACCT#294]
hey, here is a puzzle about mojofm implementation in File `src/husacct/analyse/task/reconstruct/mojo/MoJoCalculator.java`, the method used to calculate maxDistance in mojofm algo.

in that paper cap 4.2, An effectiveness measure for software clustering algorithms, of  Zhihua Wen, **I think the n - g means find another partition of B‘ far from A, so use A to generate a new B’, which get the same dist of max(mno(any_A, B)) and max(mno(B, any_A)).**

so I think the input of this method to get max dist is A, the src clusters, instead of B to generate a new B', right?

![image](https://user-images.githubusercontent.com/14577931/47951185-36ab0200-df98-11e8-98c9-2e14088cda5a.png)

i am not sure about that, hope to get your ans, thanks.

![image](https://user-images.githubusercontent.com/14577931/47951251-fef08a00-df98-11e8-9769-dacf61cfea84.png)

**Comment by LeoHU** [comment]
Hi, we did not write the code of MoJoCalculator.java, but made use of an existing implemenation, as explained in the HUSACCT User Manual: 

4.5.3 MOJO
This Mojo functionality is intended for researchers to determine the effectiveness of an algorithm. The MoJo-tab makes it easy to calculate an effectiveness measure for software clustering algorithms based on MoJo distance as presented by Wen and Tzerpos in [15]. Their implementation (mojo.tar version 2.0, downloaded April 2016 from: http://www.cs.yorku.ca/~bil/downloads/ ) is used to calculate the MoJoFM values displayed in the UI. Wen and Tzerpos define the MoJo distance between two clusterings A and B of the same software system as the minimum number of Move or Join operations one needs to perform in order to transform either A to B or vice versa. The smaller the MoJo distance between an automatically created decompo- sitionA and the “gold standard” decompositionB, the more effective the algorithm that created A.

...

Best to contact the authors Wen and Tzerpos. Success!
